---
################################################################################
#   Section: Organizations
################################################################################
Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ../organizations/ordererOrganizations/universidadesiebs.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

        OrdererEndpoints:
            - orderer.universidadesiebs.com:7050

    - &Iebs
        Name: IebsMSP
        ID: IebsMSP

        MSPDir: ../organizations/peerOrganizations/iebs.universidadesiebs.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('IebsMSP.admin', 'IebsMSP.peer', 'IebsMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('IebsMSP.admin', 'IebsMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('IebsMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('IebsMSP.peer')"

    - &Cantabria
        Name: CantabriaMSP
        ID: CantabriaMSP

        MSPDir: ../organizations/peerOrganizations/cantabria.universidadesiebs.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CantabriaMSP.admin', 'CantabriaMSP.peer', 'CantabriaMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('CantabriaMSP.admin', 'CantabriaMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('CantabriaMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('CantabriaMSP.peer')"

################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities
################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer.universidadesiebs.com:7050
    EtcdRaft:
        Consenters:
        - Host: orderer.universidadesiebs.com
          Port: 7050
          ClientTLSCert: ../organizations/ordererOrganizations/universidadesiebs.com/orderers/orderer.universidadesiebs.com/tls/server.crt
          ServerTLSCert: ../organizations/ordererOrganizations/universidadesiebs.com/orderers/orderer.universidadesiebs.com/tls/server.crt

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

################################################################################
#   CHANNEL
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Profile
################################################################################
Profiles:

    UniversidadesGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Iebs
                - *Cantabria
            Capabilities: *ApplicationCapabilities